parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    user_uniqie_email:
        class: App\Validator\UserUniqueEmailValidator
        tags:
            - { name: validator.constraint_validator, alias: user_unique_email }
    task_schedule:
        class: App\Validator\TaskScheduleValidator
        tags:
            - { name: validator.constraint_validator, alias: task_schedule }