imports:
    - { resource: services/validators.yaml }

parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Symfony\Component\Serializer\SerializerInterface:
        factory: 'Common\Service\SerializerFactory:create'
    Common\:
        resource: '../src/Common/*'
        exclude: '../src/Common/{Migrations}'
    Common\Controller\:
        resource: '../src/Common/Controller'
        tags: ['controller.service_arguments']
    Common\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    Task\:
        resource: '../src/Task/*'
    Task\Controller\:
        resource: '../src/Task/Controller'
        tags: ['controller.service_arguments']
    Task\ParamConverter\ScheduledTaskByUserParamConverter:
        tags:
            - { name: request.param_converter, converter: scheduled_task_by_user }
        arguments:
            - '@doctrine'
    User\:
        resource: '../src/User/*'
    User\Controller\:
        resource: '../src/User/Controller'
        tags: ['controller.service_arguments']
    User\Doctrine\EventListener\UserListener:
        tags: ['doctrine.orm.entity_listener']