doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '10.5'
        host: '%env(resolve:POSTGRES_HOST)%'
        port: '%env(resolve:POSTGRES_PORT)%'
        dbname: '%env(resolve:POSTGRES_DB)%'
        user: '%env(resolve:POSTGRES_USER)%'
        password: '%env(resolve:POSTGRES_PASSWORD)%'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        types:
            task_change_state: App\Doctrine\DBAL\Type\TaskChangeStateType
            task_change_action: App\Doctrine\DBAL\Type\TaskChangeActionType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
