gesdinet_jwt_refresh_token:
    ttl: '%env(int:resolve:JWT_REFRESH_TOKEN_TTL)%'
    user_identity_field: email
    user_provider: security.user.provider.concrete.user_provider
    # @todo бандл выдает каждый раз новый refresh-токен, должно ли так быть?