- name: Create deploy user
  user:
    name: '{{ deploy__user }}'
    groups:
      - '{{ www_user }}'
      - docker
    password: '{{ deploy__password | password_hash("sha512") }}'
    createhome: yes
    home: /var/www/tracker

- name: Change www directory owner to deploy user
  command: find /var/www -exec chown -R deploy:www-data {} \;

- name: Allow restart php-fpm by deploy user
  lineinfile:
    path: /etc/sudoers
    line: 'deploy ALL=NOPASSWD:/bin/systemctl restart php7.1-fpm'