- name: Create deploy user
  user:
    name: '{{ deploy__user }}'
    groups:
      - '{{ www_user }}'
    password: '{{ deploy__password }}' # todo: Не удается войти с заданным паролем, нужно разобраться.

- name: Change www directory owner to deploy user
  command: find /var/www -exec chown -R deploy:www-data {} \;

- name: Allow restart php-fpm by deploy user
  lineinfile:
    path: /etc/sudoers
    line: 'deploy ALL=NOPASSWD:/bin/systemctl restart php7.1-fpm'