domain: api.tracker.seniorcote.com
root_dir: /var/www/tracker/current/backend/public
www_user: www-data
letsencrypt_email: dev@seniorcote.com
nginx__sites_available_dir: /etc/nginx/sites-available
nginx__sites_enabled_dir: /etc/nginx/sites-enabled
nginx__nginx_conf_template: nginx.conf.j2
nginx__host_site_template: nginx_host_site.j2
nginx__host_site_filename: api.tracker.seniorcote.com
nginx__host_letsencrypt_template: nginx_host_letsencrypt.j2
nginx__host_letsencrypt_filename: letsencrypt
php__www_conf: /etc/php/7.1/fpm/pool.d/www.conf
php__php_ini: /etc/php/7.1/fpm/php.ini
postgres__pg_hba_conf: pg_hba.conf
postgres__database: tracker
postgres__user: '{{ vault_postgres_user }}'
postgres__password: '{{ vault_postgres_password }}'