- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart php-fpm
  service:
    name: php7.1-fpm
    state: restarted

- name: restart postgresql
  service:
    name: postgresql
    state: restarted